### PR TITLE
bug/scraper-cleaner-ingestion-models-2

### PR DESCRIPTION
**Pull request by dphoria**
### Link to Relevant Issue

https://github.com/CouncilDataProject/cdp-scrapers/pull/8#issuecomment-898785310
https://github.com/CouncilDataProject/cdp-scrapers/pull/16

### Description of Changes

`legistar_utils.str_simplified()` : fixed whitespace unifying; multiple consecutive whitespace to "[space]"

`LegistarScraper.get_person()` : "(###)..." -> "###-..."

### Questions ###

We noticed unicode characters `MinutesItem` and/or `Matter` in some cases. e.g. "...items during the meeting\u2019s public comment..." They were brought up in https://github.com/CouncilDataProject/cdp-scrapers/pull/8 for cleaning, but I propose that we keep them.

If we do clean them, do we just replace all \uxxxx unicode characeters to nothing ""?

### CODE REVIEW

**Review by JacksonMaxfield — APPROVED** [review]

**Comment by JacksonMaxfield** [comment]
Answering:

> We noticed unicode characters MinutesItem and/or Matter in some cases. e.g. "...items during the meeting\u2019s public comment..." They were brought up in #8 for cleaning, but I propose that we keep them.
> 
> If we do clean them, do we just replace all \uxxxx unicode characeters to nothing ""?

I mean in that exact case the `\u` is meant to be a space. From "...items during the meeting\u2019s public comment..." to "...items during the meeting 2019s public comment..." I would replace all `\u` with a ` `.

**Comment by dphoria** [comment]
I think those are in fact unicode characters. e.g.
```python
print("meeting\u2019s public comment") # meeting’s public comment
```

We are seeing them as-is because we are inspecting the `str` attributes of these models, not printing them, I believe. Same in the other example from the [king-county-scraper PR](https://github.com/CouncilDataProject/cdp-scrapers/pull/8#pullrequestreview-729002563),

```python
print("meeting by telephone \u2013 See \u201cConnecting") # meeting by telephone – See “Connecting
```

So I think we should keep them? No?...

**Comment by JacksonMaxfield** [comment]
> I think those are in fact unicode characters. e.g.
> 
> ```python
> print("meeting\u2019s public comment") # meeting’s public comment
> ```
> 
> We are seeing them as-is because we are inspecting the `str` attributes of these models, not printing them, I believe. Same in the other example from the [king-county-scraper PR](https://github.com/CouncilDataProject/cdp-scrapers/pull/8#pullrequestreview-729002563),
> 
> ```python
> print("meeting by telephone \u2013 See \u201cConnecting") # meeting by telephone – See “Connecting
> ```
> 
> So I think we should keep them? No?...

Ahhhhh I see... In that case.... I am not sure how we handle them... We only see these issues on minutes that should be filtered out anyway right? Let's keep them then...

**Comment by JacksonMaxfield** [comment]
Woops sorry @dphoria. After my last comment I should have asked if this is ready to merge. Don't know if you wanted to add anything else.

**Comment by JacksonMaxfield** [comment]
You should be able to merge whenever as you have write access to the repo.

**Comment by dphoria** [comment]
Thanks. I thought I'd wait for https://github.com/CouncilDataProject/cdp-scrapers/pull/8 then merge that into my fork. Thought that would be cleaner. Especially since this is a much smaller diff set than Dhanya's PR.

**Comment by JacksonMaxfield** [comment]
Ahhh makes sense.

**Comment by JacksonMaxfield** [comment]
@dphoria merge whenever you want

**Comment by dphoria** [comment]
Whenever you have time, take one last quick look at the changes please. I've got all I want in there for this PR.

**Review by JacksonMaxfield — APPROVED** [review]
Nice! Looks good to me!

**Pull request merged**
