### PR TITLE
bugfix/seattle-multi-session-meeting-videos

### LINKED ISSUE #38: Determine why multi-session event wasn't picked up (Seattle)
https://councildataproject.org/seattle-staging/#/events/0a6849cdbe93

Minutes Items reference multi-session but the only session for the event in our system is actually the second session of the day.

Need to debug and fix multi-session events.

### PR DESCRIPTION
**Pull request by dphoria**
### Link to Relevant Issue

This pull request resolves #38 

### Description of Changes

seattle.legistar.com links to a generic video list page like https://www.seattlechannel.org/BudgetCommittee?Mode2=Video without specific `videoid` if a given meeting has multiple sessions, hence videos.

`SeattleScraper.get_content_uris()` changes:

URL to seattlechannel.org from web page at `EventInSiteURL` contains `videoid`  
- call `parse_content_uris()` to get video and caption URIs.

URL does not contain `videoid`  
- call `get_video_page_urls()` to get URLs to seattlechannel.org with `videoid` for the given meeting  
- call `parse_content_uris()` to get video and caption URIs.

`SeattleScraper.parse_content_uris()` changes:

Raise `ValueError` if video player setup script does not contain the meeting's date in video `idstring`.

### CODE REVIEW

**Comment by dphoria** [comment]
Thoughts on raising `ValueError` when the video hosting web page does not actually have the correct video? Different standard exception, or some custom one?

**Comment by dphoria** [comment]
Just FYI @dhanya-shraddha , Jackson recently found out `SeattleScraper` just did not work at all for meetings with multiple sessions :sweat_smile: . We found out "video" link on `EventInSiteURL` does not contain video ID in the URL. So now it first gets the right URLs to the web page(s) for the video(s), then call existing method that parses for video/caption URIs. This is all Seattle stuff.

**Comment by dphoria** [comment]
Thought I'd make use of the Notes section https://numpydoc.readthedocs.io/en/latest/format.html#notes.

> provides additional information about the code, possibly including a discussion of the algorithm

**Review by JacksonMaxfield — APPROVED** [review]
Perfect!! Thank you!

**Pull request merged**
