### PR TITLE
bugfix/seattle-nelson-picture-uri

### PR DESCRIPTION
**Pull request by dphoria**
### Link to Relevant Issue

Previous picture for Sara Nelson does not work in thumbnail form on the people page in our frontend web site. We want pictures that have the person in the center of the image.

### Description of Changes

_Include a description of the proposed changes._

Changed `picture_uri` for Sara Nelson to http://www.seattle.gov/images/Council/Members/Nelson/nelson_300x300.jpg

### CODE REVIEW

**Comment by dphoria** [comment]
Great question. I'm getting the URL as-is from her profile page on seattle.gov. Having said that, I've tried just forcing https and it does load. Having http for the image URLs clearly haven't mattered for us so far.

So, I guess I'm undecisive; changing to https at least for Nelson seems to be fine. Or, do we go ahead and change `Person.picture_uri` for everyone in Seattle to use https (after checking the resources are still accessible over https)? What do you think? Or just leave them alone?

Also what do you think @JacksonMaxfield ?

**Comment by tohuynh** [comment]
> Having http for the image URLs clearly haven't mattered for us so far.

If it hasn't affected our ability to download the image, then let's keep it as what we have now.

**Comment by dphoria** [comment]
I agree. Actually now I'm remember there is code in `cdp-backend` that does try `https` and use that form if loadable.

**Comment by dphoria** [comment]
So yeah I think leave them as-is here, for "consistency" and not-change-unless-necessary-sake... Not strong either way. I'll let Jackson decide LOL.

**Comment by JacksonMaxfield** [comment]
Unfortunately the code the fixes http -> https only affects the session video uri. That seems like an oversight and I will be adding an issue to track hahaha.

For now, please update this uri to `https` please!

**Review by JacksonMaxfield — APPROVED** [review]

**Comment by dphoria** [comment]
Checked all images for Seattle `Persons` and `Seats` are accessible over `https` (Chromium and Firefox).

**Pull request merged**
