### PR TITLE
enhancement/more-seattle-minute-item-filters

### LINKED ISSUE #37: Filter out more minutes items for seattle
* `Pending, Potential, or Actual Litigation` ("Executive Session I on Pending, Potential, or Actual Litigation*", and "Executive Session II on Pending, Potential, or Actual Litigation*") -- https://councildataproject.org/seattle-staging/#/events/b16568a04e96
* `Pursuant to Washington State` ("Pursuant to Washington State Governor’s Proclamation No. 20-28.15 and Senate Concurrent Resolution 8402, this public meeting will be held remotely. Meeting participation is limited to access by the telephone number provided on the meeting agenda, and the meeting is accessible via telephone and Seattle Channel online.") -- https://councildataproject.org/seattle-staging/#/events/ad8236ceec45

### PR DESCRIPTION
**Pull request by dphoria**
### Link to Relevant Issue

This pull request resolves #37 

### Description of Changes

Updated `SeattleScraper.ignore_minutes_item_patterns` to filter out more irrelevant information from ingesting as `EventMinutesItem`.

- "Executive Session [ session number ] on Pending, Potential, or Actual Litigation"
 Similar pattern already existed. Updated to optionally match session number like "Session I"

- "Pursuant to Washington State"
 To filter out unimportant items that begin with this string and contain phrases like "this public meeting will be held remotely".

### CODE REVIEW

**Comment by dphoria** [comment]
Not used to legislature language, is there concern that "Pursuant to Washington State" is too broad and can filter out meaningful minutes items? Should I use something else like `r"this .*meeting will be held remotely"`?

**Comment by dphoria** [comment]
/test-scraper get_seattle_events --from_dt=2021-10-04T00:00:00 --to_dt=2021-10-05T00:00:00

**Comment by JacksonMaxfield** [comment]
> Not used to legislature language, is there concern that "Pursuant to Washington State" is too broad and can filter out meaningful minutes items? Should I use something else like `r"this .*meeting will be held remotely"`?

This is a good question. Tbh I'm not too worried about it. My mental model for this is like "if a minutes item is using full sentences.... it's probably a filterable thing"

**Comment by dphoria** [comment]
/test-scraper get_seattle_events --from_dt=2021-10-11T00:00:00 --to_dt=2021-10-12T00:00:00

**Comment by dphoria** [comment]
> > Not used to legislature language, is there concern that "Pursuant to Washington State" is too broad and can filter out meaningful minutes items? Should I use something else like `r"this .*meeting will be held remotely"`?
> 
> This is a good question. Tbh I'm not too worried about it. My mental model for this is like "if a minutes item is using full sentences.... it's probably a filterable thing"

Ooh like the reasoning.

**Review by JacksonMaxfield — APPROVED** [review]
This looks good to me! Thanks for handling this. Going to merge.

Random comment. It may be useful (in the future) to add to the test scraper command the ability to compare this PR branch vs the merge target branch.

Run both and then generate a diff between the produced JSONs.

**Comment by JacksonMaxfield** [comment]
My above comment is very low priority

**Comment by dphoria** [comment]
> This looks good to me! Thanks for handling this. Going to merge.
> 
> Random comment. It may be useful (in the future) to add to the test scraper command the ability to compare this PR branch vs the merge target branch.
> 
> Run both and then generate a diff between the produced JSONs.

I like it! Galaxy brain. And very minor thought; I'd like to title the job so I don't have to filter through 5 billion actions with the same name. Just can't remember if I can change the title through the `yaml` file. I'll figure it out, not super important.

**Comment by dphoria** [comment]
Actually I'm pretty sure I AM giving it the title in `yaml`. ANyway will stop commenting on closed PR :sweat_smile:

**Pull request merged**
