### PR TITLE
admin/bump-version

### PR DESCRIPTION
**Pull request by dphoria**
### Description of Changes

_Include a description of the proposed changes._

`bumpversion patch` from `0.3.2` to `0.3.3`.

### CODE REVIEW

**Comment by dphoria** [comment]
First time, so just want to check @JacksonMaxfield . I did `bumpversion patch`. Yay or nay?...

**Comment by JacksonMaxfield** [comment]
Oh wowowow, don't do this in a PR. Do it on main. https://github.com/CouncilDataProject/cdp-scrapers/blob/main/CONTRIBUTING.md#deploying

This commit history should probably be cleaned up as well. You should like pull / rebase remote main to your local main. It should only be adding a single commit in a single push.

**Comment by JacksonMaxfield** [comment]
(This is the one part of the process of package management that happens directly on main)

**Comment by dphoria** [comment]
Gotcha. Thanks. And ugh I missed that part in the doc.

**Pull request closed without merging**
