### PR TITLE
bugfix/seattle-more-multi-session-meeting-videos

### LINKED ISSUE #48: SeattleScraper not getting multiple sessions for some dates
### Describe the Bug

A meeting from [10/26](https://seattle.legistar.com/MeetingDetail.aspx?ID=893277&GUID=978A2256-75D4-4764-B477-FB31C7025DC6&Options=info|&Search=) is a multi-session meeting with multiple videos. `SeattleScraper.get_events()`, however, returns just 1 `session`.

The scraper does return multiple `sessions` correctly for other multi-session meetings, such as one from [10/15](https://seattle.legistar.com/MeetingDetail.aspx?ID=893276&GUID=EB1FCB44-77C7-4633-BF80-437A9AA309A8&Options=info|&Search=).

### Expected Behavior

`EventIngestionModel` object returned from `SeattleScraper.get_events(begin=datetime(2021, 10, 26), end=datetime(2021, 10, 27))` to contain 2 `sessions`.

### Reproduction

```Python
from cdp_scrapers.instances.seattle import SeattleScraper
from datetime import datetime
begin = datetime(2021, 10, 26)
end = datetime(2021, 10, 27)
s = SeattleScraper()
events = s.get_events(begin=begin, end=end)
print(events[0].to_json(indent=4))
```

### Environment

_Any additional information about your environment._

-   `cdp-scrapers` version: 0.3.2
-   CDP Backend Version: 3.0

### PR DESCRIPTION
**Pull request by dphoria**
### Link to Relevant Issue

This pull request resolves #48 

### Description of Changes

Improved `SeattleScraper.get_content_uris()`.

We had previously though it was a rule that meetings with multiple `sessions` would have generic video links without `videoid` in the URLs. That has been proven to not be the case.

When a meeting's description clearly specifies the presence of multiple `sessions`, we will treat it as such, even if the video URL linked on the details web page contains a specific `videoid`.

### CODE REVIEW

**Comment by dphoria** [comment]
/test-scraper get_seattle_events --from_dt=2021-10-15T00:00:00 --to_dt=2021-10-26T00:00:00

**Comment by dphoria** [comment]
/test-scraper get_seattle_events --from_dt=2021-10-15T00:00:00 --to_dt=2021-10-27T00:00:00

**Comment by dphoria** [comment]
The event from 10/26 is a multi-session meeting, with `videoid` in the video URL. The PR code should now correctly retrieve both `sessions`.
Event from 10/15 is the "old" style multi-session meeting withOUT `videoid`; the PR code should still retrieve both `sessions` for this event.

**Comment by dphoria** [comment]
CC'ing @Shak2000; couldn't set as reviewer.

**Comment by JacksonMaxfield** [comment]
@dphoria if I don't look at this within the next three days please ping me again :joy:

**Comment by dphoria** [comment]
> @dphoria if I don't look at this within the next three days please ping me again joy

LOL yup you got it!

**Review by JacksonMaxfield — APPROVED** [review]
Oh this was a way easier change than I thought this was. Should have looked sooner hahaha.

**Comment by JacksonMaxfield** [comment]
Feel free to merge whenever!

**Comment by JacksonMaxfield** [comment]
Actually I am merging now because I think I need this to test something...

**Comment by dphoria** [comment]
> Oh this was a way easier change than I thought this was. Should have looked sooner hahaha.

No `cdp-backend` had a much more serious issue :sweat_smile:

**Pull request merged**
